# Generated by Django 5.2.7 on 2025-10-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField()),
                ('time_planted', models.DateTimeField()),
                ('time_watered', models.DateTimeField()),
                ('health', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField()),
                ('scientific_name', models.CharField()),
                ('status', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
