# Generated by Django 5.2.6 on 2025-10-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('position', models.CharField()),
                ('time_planted', models.DateTimeField()),
                ('time_watered', models.DateTimeField()),
                ('health', models.CharField()),
            ],
        ),
    ]
