# Generated by Django 5.2.7 on 2025-11-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenplant',
            name='time_planted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='time_watered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
