# Generated by Django 5.2.7 on 2025-10-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0002_gardenplant_planttype_delete_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='growth_rate',
            field=models.CharField(default='NULL'),
        ),
    ]
