# Generated by Django 5.2.7 on 2025-11-02 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0002_alter_gardenplant_time_planted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenplant',
            name='health',
            field=models.CharField(default='Healthy', max_length=50),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='position',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GardenWise.planttype'),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
