# Generated by Django 5.2.7 on 2025-11-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0003_alter_gardenplant_health_alter_gardenplant_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenplant',
            name='notes',
        ),
        migrations.RenameField(
            model_name='gardenplant',
            old_name='type',
            new_name='plant_type',
        ),
        migrations.RemoveField(
            model_name='gardenplant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='planttype',
            name='facts',
        ),
        migrations.RemoveField(
            model_name='planttype',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='planttype',
            name='watering_time',
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='garden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to='GardenWise.garden'),
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='plant_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='GardenWise.planttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='health',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='position',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='time_planted',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-02T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='time_watered',
            field=models.DateTimeField(auto_now=True, default='2025-11-02T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planttype',
            name='growth_rate',
            field=models.CharField(default='NULL'),
        ),
    ]
