# Generated by Django 5.2.7 on 2025-10-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0003_planttype_growth_rate'),
    ]

    operations = [
    ]
