# Generated by Django 5.2.7 on 2025-10-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0003_planttype_growth_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='ph',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='planttype',
            name='temperture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='scientific_name',
            field=models.CharField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='status',
            field=models.CharField(default='NULL'),
        ),
    ]
