# Generated by Django 5.2.7 on 2025-10-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0004_planttype_ph_planttype_temperture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='ph',
            field=models.FloatField(default=0.0),
        ),
    ]
