# Generated by Django 5.2.7 on 2025-11-02 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0004_remove_gardenplant_notes_remove_gardenplant_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenplant',
            name='garden',
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='health',
            field=models.CharField(blank=True, default='Healthy', max_length=100),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='plant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GardenWise.planttype'),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='time_planted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='time_watered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
