# Generated by Django 5.2.7 on 2025-11-02 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0005_remove_gardenplant_garden_gardenplant_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenplant',
            name='garden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GardenWise.garden'),
            preserve_default=False,
        ),
    ]
