# Generated by Django 5.2.7 on 2025-11-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0006_gardenplant_garden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='ph',
            field=models.CharField(default='NULL'),
        ),
    ]
