# Generated by Django 5.2.7 on 2025-10-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0007_alter_planttype_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='temperture',
            field=models.IntegerField(default=0),
        ),
    ]
