# Generated by Django 5.2.7 on 2025-11-15 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0007_alter_planttype_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenplant',
            name='time_planted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='time_watered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
