# Generated by Django 5.2.7 on 2025-11-15 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0008_alter_gardenplant_time_planted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenplant',
            name='time_planted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='time_watered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
