# Generated by Django 5.2.7 on 2025-10-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0008_alter_planttype_temperture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='ph',
            field=models.FloatField(default=None),
        ),
    ]
