# Generated by Django 5.2.7 on 2025-11-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0009_alter_gardenplant_time_planted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(default='My Garden', max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_garden_name_per_user'),
        ),
    ]
