# Generated by Django 5.2.7 on 2025-10-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0009_alter_planttype_ph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planttype',
            name='ph',
        ),
    ]
