# Generated by Django 5.2.7 on 2025-11-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0010_alter_garden_name_garden_unique_garden_name_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(default='My Garden', max_length=255),
        ),
    ]
