# Generated by Django 5.2.7 on 2025-10-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0010_remove_planttype_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='ph',
            field=models.FloatField(default=0.0),
        ),
    ]
