# Generated by Django 5.2.6 on 2025-10-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0004_auto_20251021_0151'),
        ('GardenWise', '0011_planttype_ph'),
    ]

    operations = [
    ]
