# Generated by Django 5.2.7 on 2025-11-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0011_alter_garden_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='category',
            field=models.CharField(default='vegetable', max_length=50),
        ),
    ]
