# Generated by Django 5.2.7 on 2025-10-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0012_merge_0004_auto_20251021_0151_0011_planttype_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='season',
            field=models.CharField(default='NULL'),
        ),
        migrations.AddField(
            model_name='planttype',
            name='zone',
            field=models.CharField(default='NULL'),
        ),
    ]
