# Generated by Django 5.2.7 on 2025-11-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0012_planttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
