# Generated by Django 5.2.7 on 2025-10-30 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0012_merge_0004_auto_20251021_0151_0011_planttype_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenplant',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='GardenWise.planttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='health',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='time_planted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='time_watered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Garden', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='garden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to='GardenWise.garden'),
        ),
    ]
