# Generated by Django 5.2.7 on 2025-10-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0013_planttype_season_planttype_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planttype',
            name='status',
        ),
    ]
