# Generated by Django 5.2.7 on 2025-12-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0013_account_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zone',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
