# Generated by Django 5.2.7 on 2025-10-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0014_remove_planttype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='temperture',
            field=models.CharField(default='NULL'),
        ),
    ]
