# Generated by Django 5.2.7 on 2025-10-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0015_alter_planttype_temperture'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='spacing',
            field=models.CharField(default='NULL'),
        ),
    ]
