# Generated by Django 5.2.7 on 2025-10-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0016_planttype_spacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenplant',
            name='notes',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='planttype',
            name='facts',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='planttype',
            name='soil',
            field=models.CharField(default='NULL'),
        ),
        migrations.AddField(
            model_name='planttype',
            name='watering_time',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='health',
            field=models.CharField(default='NULL'),
        ),
    ]
