# Generated by Django 5.2.7 on 2025-10-29 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0017_gardenplant_notes_planttype_facts_planttype_soil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenplant',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GardenWise.planttype'),
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
