# Generated by Django 5.2.7 on 2025-10-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenWise', '0018_gardenplant_type_gardenplant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='growth_rate',
            field=models.IntegerField(default=0),
        ),
    ]
